config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  get 'profile/dashboard'
  resources :users do
   resources :profile
  end
  get 'home/index'

   root 'home#index'
   resources :branch , only: [:index, :show]do
    resources :semester, only: [:index, :show]do
      resources :subject, only: [:index, :show] do
        resources :unit, only: [:index, :show]
      end
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/branch.rb
class Branch < ActiveRecord::Base
	has_many :users
end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	
end

app/models/semester.rb
class Semester < ActiveRecord::Base
	
end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/unit.rb
class Unit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :send_signup_mail
  
  	has_one :profile
    has_one :branch

    def send_signup_mail
      UserMailer.signup_mail(self).deliver
    end      

   #  def full_name
   #  	"#{first_name} #{last_name}"
  	# end 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/branch_helper.rb
module BranchHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/semester_helper.rb
module SemesterHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <h3>Acadmica</h3>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="widget">
                    <h6 class="title">Updates</h6>
                    <hr>
                    <ul class="link-list recent-posts">
                      
                        <li>
                            <a href="#">Dummy book</a>
                        </li>               
                    </ul>
                </div>
                <!--end of widget-->
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="widget">
                    <h6 class="title">Latest Updates</h6>
                    <hr>
                    <div class="twitter-feed">
                        <div class="tweets-feed" data-widget-id="492085717044981760">
                        </div>
                    </div>
                </div>
                <!--end of widget-->
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="widget">
                    <h6 class="title">Instagram</h6>
                    <hr>
                    <<!-- div class="instafeed" data-user-name="funsizeco">
                        <ul></ul>
                    </div> -->
                </div>
                <!--end of widget-->
            </div>
        </div>
        <!--end of row-->
        <div class="row">
          <div class="col-sm-6">
            <span class="sub">&copy; Copyright 2016 - Acadmica</span>
          </div>
            <div class="col-sm-6 text-right">
              <ul class="list-inline social-list">
                <li>
                  <a href="#">
                      <i class="ti-twitter-alt"></i>
                  </a>
                </li>
                <li>
                    <a href="#">
                        <i class="ti-facebook"></i>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="ti-dribbble"></i>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="ti-vimeo-alt"></i>
                    </a>
                </li>
                </ul>
            </div>
          </div>
        </div>
    <!--end of container-->
        <a class="btn btn-sm fade-half back-to-top inner-link" href="#top">Top</a>
      </footer>

app/views/layouts/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
            </button>
            <%= link_to 'Acadmica', root_path, class:"navbar-brand page-scroll" %> 
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <% unless user_signed_in?  %>
                <li>
                    <a class="page-scroll" href="#">About</a>
                </li>
                <li>
                    <a class="page-scroll" href="#">Services</a>
                </li>
                <li>
                    <li><%= link_to 'Log in', new_user_session_path%></li>
                </li>
                <li>
                    <%= link_to 'Sign up', new_user_registration_path%>
                 </li>
                 <% end %>
                 <% if user_signed_in? %>
                 <li> 
                    <%= link_to 'Branch', branch_index_path%>
                </li>
                
                 <li> 
                    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
                </li>

            <% end %>
        </ul>
    </div>
    <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Csnotes</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navbar'%> <!-- Navbar -->

	<div class="flash-notice text-center">  <!-- Flash Massages -->
		<%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
		<%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
		<%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
	</div>
	<script type="text/javascript">
		setTimeout(function() {
			$('.flash-notice').slideUp('slow');
	}, 10000); // <-- time in milliseconds


</script>
<%= yield %>
<%= render 'layouts/footer'%>
</body>
</html>